import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/frameseven">FrameSeven</Link>
        </li>
        <li>
          <Link to="/framefour">FrameFour</Link>
        </li>
        <li>
          <Link to="/frameeight">FrameEight</Link>
        </li>
        <li>
          <Link to="/framethree">FrameThree</Link>
        </li>
        <li>
          <Link to="/frametwo">FrameTwo</Link>
        </li>
        <li>
          <Link to="/framesix">FrameSix</Link>
        </li>
        <li>
          <Link to="/frame">Frame</Link>
        </li>
        <li>
          <Link to="/framefive">FrameFive</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
