export const records = [
    {
      code:"DCIT101",
      title:"INTRODUCTION TO COMPUTER SCIENCE",
      credit: 3,
      grade:"A",
      gpt:12,
    },
    {
      code: "DCIT103",
      title: "OFFICE PRODUCTIVITY TOOLS",
      credit: 3,
      grade: "A",
      gpt:12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "MATH121",
      title: "ALGEBRA AND TRIGONOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "MATH123",
      title: "VECTORS AND GEOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "STAT111",
      title: "INTRODUCTION TO STATISTICS AND PROBABILITY I ",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "UGRC150",
      title: "CRITICAL THINKING AND PRACTICAL REASONING ",
      credit: 3,
      grade: "B+",
      gpt: 10.5,
      year:"2022/23",
      sem: 1,
    },
  ]

  export const records2 = [
    {
      code:"DCIT102",
      title:"COMPUTER HARDWARE FUNDAMENTALS AND CIRCUITS",
      credit: 3,
      grade:"A",
      gpt:12,
    },
    {
      code: "DCIT104",
      title: "PROGRAMMING FUNDAMENTALS",
      credit: 3,
      grade: "A",
      gpt:12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "MATH122",
      title: "CALCULUS I",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "MATH126",
      title: "ALGEBRA AND GEOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "STAT112",
      title: "INTRODUCTION TO STATISTICS AND PROBABILITY II",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "UGRC110",
      title: "ACADEMIC WRITING I ",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
  ]


  export const records3 = [
    {
      code:"DCIT201",
      title:"PROGRAMMING I",
      credit: 3,
      grade:"N/A",
      gpt:"N/A",
      year:"2023/24",
      sem:1,
    },
    {
      code: "DCIT203",
      title: "DIGITAL AND LOGIC SYSTEMS DESIGN",
      credit: 3,
      grade: "N/A",
      gpt:"N/A",
      year:"2023/24",
      sem: 1,
    },
    {
      code: "DCIT205",
      title: "MULTI MEDIA AND WEB DESIGN ",
      credit: 3,
      grade: "N/A",
      gpt: "N/A",
      year:"2023/24",
      sem: 1,
    },
    {
      code: "DCIT207",
      title: "COMPUTER ORGANIZATION & ARCHITECTURE",
      credit: 3,
      grade: "N/A",
      gpt: "N/A",
      year:"2023/24",
      sem: 1,
    },
    {
      code: "STAT112",
      title: "INTRODUCTION TO STATISTICS AND PROBABILITY II",
      credit: 3,
      grade: "N/A",
      gpt: "N/A",
      year:"2022/23",
      sem: 2,
    },
    {
      code: "MATH223",
      title: "CALCULUS II",
      credit: 3,
      grade: "N/A",
      gpt: "N/A",
      year:"2023/24",
      sem: 1,
    },
  ]