export const records = [
    {
      code:"DCIT101",
      title:"INTRODUCTION TO COMPUTER SCIENCE",
      credit: 3,
      grade:"A",
      gpt:12,
    },
    {
      code: "DCIT103",
      title: "OFFICE PRODUCTIVITY TOOLS",
      credit: 3,
      grade: "A",
      gpt:12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "MATH121",
      title: "ALGEBRA AND TRIGONOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "MATH123",
      title: "VECTORS AND GEOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "STAT111",
      title: "INTRODUCTION TO STATISTICS AND PROBABILITY I ",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 1,
    },
    {
      code: "UGRC150",
      title: "CRITICAL THINKING AND PRACTICAL REASONING ",
      credit: 3,
      grade: "B+",
      gpt: 10.5,
      year:"2022/23",
      sem: 1,
    },
  ]

  export const records2 = [
    {
      code:"DCIT102",
      title:"COMPUTER HARDWARE FUNDAMENTALS AND CIRCUITS",
      credit: 3,
      grade:"A",
      gpt:12,
    },
    {
      code: "DCIT104",
      title: "PROGRAMMING FUNDAMENTALS",
      credit: 3,
      grade: "A",
      gpt:12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "MATH122",
      title: "CALCULUS I",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "MATH126",
      title: "ALGEBRA AND GEOMETRY",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "STAT112",
      title: "NTRODUCTION TO STATISTICS AND PROBABILITY II",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
    {
      code: "UGRC110",
      title: "ACADEMIC WRITING I ",
      credit: 3,
      grade: "A",
      gpt: 12,
      year:"2022/23",
      sem: 2,
    },
  ]