export const GradesData = [
  {
    courseTitle: "",
    courseCode: "DCIT 201",
    instructor: "Mr. Sobe Senyo",
    instructorEmail: "ssenyou@academiawave.edu.com",
    grade: "B+",
    timeUploaded: "6d",
  },
  {
    courseTitle: "",
    courseCode: "DCIT 203",
    instructor: "Mr. Kweku Mensah",
    instructorEmail: "kmensah@academiawave.edu.com",
    grade: "B",
    timeUploaded: "1w",
  },
  {
    courseTitle: "",
    courseCode: "DCIT 209",
    instructor: "Dr. Mensah Sarbah",
    instructorEmail: "msarbah@academiawave.edu.com",
    grade: "N/A",
    timeUploaded: "4d",
  },
  {
    courseTitle: "",
    courseCode: "DCIT 205",
    instructor: "Dr. Michael Soli",
    instructorEmail: "msoli@academiawave.edu.com",
    grade: "N/A",
    timeUploaded: "2d",
  },
  {
    courseTitle: "",
    courseCode: "MATH 223",
    instructor: "Dr. John Ansah",
    instructorEmail: "jansah@academiawave.edu.com",
    grade: "A",
    timeUploaded: "3d",
  },
  {
    courseTitle: "",
    courseCode: "MATH 225",
    instructor: "Dr. Eugene Adjei",
    instructorEmail: "eadjei@academiawave.edu.com",
    grade: "N/A",
    timeUploaded: "3h",
  },
  {
    courseTitle: "",
    courseCode: "CBAS 210",
    instructor: "Mr. Kasim Smith",
    instructorEmail: "ksmith@academiawave.edu.com",
    grade: "A",
    timeUploaded: "1h",
  },
  {
    courseTitle: "",
    courseCode: "MATH 220",
    instructor: "Dr. Erwin Schrowdinger",
    instructorEmail: "eschrowdinger@academiawave.edu.com",
    grade: "B+",
    timeUploaded: "4h",
  },
  {
    courseTitle: "",
    courseCode: "DCIT 207",
    instructor: "Mr. Samuel Minge",
    instructorEmail: "smingeu@academiawave.edu.com",
    grade: "B",
    timeUploaded: "3w",
  },
];
